# Generated by Django 4.2.15 on 2024-11-03 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("zipcode", models.CharField(max_length=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("number_of_bedrooms", models.IntegerField()),
                (
                    "number_of_bathrooms",
                    models.DecimalField(decimal_places=1, max_digits=4),
                ),
                ("square_footage", models.IntegerField()),
                ("year_built", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="accounts.user"
                    ),
                ),
            ],
        ),
    ]
