# Generated by Django 4.2.16 on 2024-11-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_house"),
    ]

    operations = [
        migrations.RemoveField(model_name="user", name="full_name",),
        migrations.AlterField(
            model_name="user", name="user_type", field=models.CharField(max_length=20),
        ),
    ]
